[wip] More schema.org
codeformuenster/event-api pull request #3
Opened 2017-04-16 00:44 UTC by webwurst

/ping @tomsrocket @jahnique 
Nur schon mal zur Info. Original `schema.org` Beispiele sind in den Tests und funktionieren.
Insgesamt gibt's zehn Tests.

Aber ein bisschen was muss noch gedreht werden und auch noch besser getestet bevor das deployed werden kann. Vielleicht ändern sich auch noch Details an der API, damit die besser zu Schema.org passt.

2017-04-17 00:41 UTC, tomsrocket commented
Ähh.. find ich prinzipiell gut, dass du was machst und das projekt nach vorne bringst, aber unabgesprochen so viel umstellen find ich uncool.

2017-04-17 08:33 UTC, webwurst commented
Ja, ok. Aber können wir ja hier diskutieren im pull-request. Tatsächlich hätte ich hier ein paar mehr Hintergrundinfos angeben können.

- Die Angabe von `lat`/`long` ist jetzt optional. Damit man bei Aufruf ohne Parameter auch was zurück bekommt.
- Wenn keine Zeit angegeben ist, dann wird nicht implizit von "now" ausgeganben. Könnte man stattdessen explizit "now" übergeben.
- Statt `lat`, `long`, `distance` separat wird ein feld `geo_distance` angegeben. damit die Validierung einfacher geht. Sonst müsste man überprüfen, dass wenn `lat`, auch `long` angegeben wird und umgekehrt.
- In die Api rein und raus gehen json-datensätze im `schema.org` format. Beispiele dazu finden sich im test-ordner. Das passt nicht auf das Elasticsearch Schema. Intern wird deshalb ein Hilfs-Feld angelegt `x-es-geopoint`. Das wird aber auch nur intern verwendet und nicht mit ausgegeben.

2017-05-02 18:29 UTC, tomsrocket requested changes
Eine kurze Info in README wäre noch gut, was man machen muss wenn diese eine kryptische Zeile nicht funktioniert..

2017-05-02 18:29 UTC, tomsrocket commented on api/events.py
> +es = elasticsearch.Elasticsearch([elasticsearch_url])
Globale Konstanten sollten UPPERCASE only sein

2017-05-02 18:29 UTC, tomsrocket commented on api/events.py
> -from elasticsearch import Elasticsearch
modul docblock wurde entfernt

2017-05-02 18:29 UTC, tomsrocket commented on api/events.py
>  import os
imports wurden wieder in die falsche reihenfolge gebracht. General to specific sollte das sein..

2017-05-02 18:29 UTC, tomsrocket commented on api/events.py
> +        logging.info(f"III: {kwargs['geo_distance']}")
was bedeutet III?

2017-05-02 18:29 UTC, tomsrocket commented on api/events.py
> +    # if category:
Warum hast du das rausgenommen?

2017-05-02 19:35 UTC, webwurst commented on api/events.py
> +        logging.info(f"III: {kwargs['geo_distance']}")
war übrid vom debuggen, nehm ich raus.

2017-05-02 19:40 UTC, webwurst commented on api/events.py
> +    # if category:
`category` ist ein paar zeilen hochgerutscht, nach `query["query"]["bool"]["should"]`

2017-05-02 19:42 UTC, webwurst commented on api/events.py
> -from elasticsearch import Elasticsearch
ok, ist wieder drin

2017-05-09 17:20 UTC, merged